### ISSUE TITLE
this is where the driver goes

### ISSUE THREAD

**Issue by Alexanderallenbrown** [joaquinfont/DeerTraining#9]
https://github.com/joaquinfont/DeerTraining/blob/fd2e27eb762c8e833b939033225f8b9277c9bde1/TrainDeer.py#L55

you will want to compute the car's inputs (steer, gas, brake) based on your driver class right here! Then, when you Heuns update, you will use those inputs rather than calling the method with autopilot and cruise on. make sure to set cruise to "off" if you are doing your own gas control, or it will be overwritten.

**Comment by joaquinfont** [comment]
Dirver class created and added to TrainDeer.py
